version: '3'
services:
  db:
    image: postgres:14.2-alpine
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: priceBTC
      PGDATA: /var/lib/postgresql/data/pgdata
    restart: always
#  web_statictics:
#    image: asalalaiko/price-btc-statistics:v2
#    ports:
#      - 8080:8080
#    restart: always
#    links:
#      - db
  trade_cex:
    image: asalalaiko/price-btc-trade-cex:v1
    ports:
      - 8081:8081
#    restart: always
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/priceBTC
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update